version: 2

jobs:
  test:
    parallelism: 1
    working_directory: ~/app
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: my-cache-{{ .Branch }}-1
      - run: npm ci
      - save_cache:
          key: my-cache-{{ .Branch }}-1-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run: npm test
      - run: npm run semantic-release

workflows:
  version: 2
  test:
    jobs:
      - test
